/*
 * anaptecs GmbH, Ricarda-Huch-Str. 71, 72760 Reutlingen, Germany
 * 
 * Copyright 2004 - 2019. All rights reserved.
 */
package com.anaptecs.jeaf.json.problem;

import com.anaptecs.jeaf.tools.api.http.HTTPStatusCode;
import com.anaptecs.jeaf.xfun.api.checks.Check;

/**
 * Class defines a "problem detail" as a way to carry machine-readable details of errors in a HTTP response to avoid the
 * need to define new error response formats for HTTP APIs.
 * 
 * Please be aware that comments about the filed are taken from IETF.
 * 
 * @see https://tools.ietf.org/html/rfc7807
 * 
 * @author JEAF Development Team
 */
public class Problem {
  /**
   * Constant for the name of attribute "type".
   */
  public static final String TYPE = "type";

  /**
   * Constant for the name of attribute "title".
   */
  public static final String TITLE = "title";

  /**
   * Constant for the name of attribute "status".
   */
  public static final String STATUS = "status";

  /**
   * Constant for the name of attribute "detail".
   */
  public static final String DETAIL = "detail";

  /**
   * Constant for the name of attribute "instance".
   */
  public static final String INSTANCE = "instance";

  /**
   * A URI reference [RFC3986] that identifies the problem type. This specification encourages that, when dereferenced,
   * it provide human-readable documentation for the problem type (e.g., using HTML [W3C.REC-html5-20141028]). When this
   * member is not present, its value is assumed to be "about:blank".
   * 
   * <b>Default Value:</b> <code>"about:blank"</code> <br/>
   */
  private String type;

  /**
   * A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence of the
   * problem, except for purposes of localization (e.g., using proactive content negotiation; see [RFC7231], Section
   * 3.4).
   */
  private String title;

  /**
   * The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
   */
  private int status;

  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  private String detail;

  /**
   * A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information
   * if dereferenced.
   */
  private String instance;

  /**
   * Default constructor is only intended to be used for deserialization as many frameworks required that. For "normal"
   * object creation builder should be used instead.
   */
  public Problem( ) {
    type = "about:blank";
  }

  /**
   * Initialize object using the passed builder.
   * 
   * @param pBuilder Builder that should be used to initialize this object. The parameter must not be null.
   */
  protected Problem( Builder pBuilder ) {
    // Ensure that builder is not null.
    Check.checkInvalidParameterNull(pBuilder, "pBuilder");
    // Read attribute values from builder.
    type = pBuilder.type;
    status = pBuilder.status;

    // For title of the problem a special behavior is expected in case that it is not set.
    if (pBuilder.title != null) {
      title = pBuilder.title;
    }
    // In case that not title is set then it should be taken according to the status code
    else {
      if (HTTPStatusCode.isOfficalStatusCode(status)) {
        title = HTTPStatusCode.fromStatusCode(status).getName();
      }
      else {
        title = "Unknown HTTP Status";
      }
    }
    detail = pBuilder.detail;
    instance = pBuilder.instance;
  }

  /**
   * Method returns a new builder.
   * 
   * @return {@link Builder} New builder that can be used to create new ImmutablePOJOParent objects.
   */
  public static Builder builder( ) {
    return new Builder();
  }

  /**
   * Method creates a new builder and initialize it with the data from the passed object.
   * 
   * @param pObject Object that should be used to initialize the builder. The parameter may be null.
   * @return {@link Builder} New builder that can be used to create new Problem objects. The method never returns null.
   */
  public static Builder builder( Problem pObject ) {
    return new Builder(pObject);
  }

  /**
   * Class implements builder to create a new instance of class Problem. As the class has read only attributes or
   * associations instances can not be created directly. Instead this builder class has to be used.
   */
  public static class Builder {
    /**
     * A URI reference [RFC3986] that identifies the problem type. This specification encourages that, when
     * dereferenced, it provide human-readable documentation for the problem type (e.g., using HTML
     * [W3C.REC-html5-20141028]). When this member is not present, its value is assumed to be "about:blank".
     * 
     * <b>Default Value:</b> <code>"about:blank"</code> <br/>
     */
    private String type = "about:blank";

    /**
     * A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence of the
     * problem, except for purposes of localization (e.g., using proactive content negotiation; see [RFC7231], Section
     * 3.4).
     */
    private String title;

    /**
     * The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
     */
    private int status;

    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    private String detail;

    /**
     * A URI reference that identifies the specific occurrence of the problem. It may or may not yield further
     * information if dereferenced.
     */
    private String instance;

    /**
     * Use {@link #newBuilder()} instead of private constructor to create new builder.
     */
    protected Builder( ) {
    }

    /**
     * Use {@link #newBuilder(Problem)} instead of private constructor to create new builder.
     */
    protected Builder( Problem pObject ) {
      if (pObject != null) {
        // Read attribute values from passed object.
        type = pObject.type;
        title = pObject.title;
        status = pObject.status;
        detail = pObject.detail;
        instance = pObject.instance;
      }
    }

    /**
     * Method sets the attribute "type".
     * 
     * @param pType Value to which the attribute "type" should be set.
     */
    public Builder setType( String pType ) {
      // Assign value to attribute
      type = pType;
      return this;
    }

    /**
     * Method sets the attribute "title".
     * 
     * @param pTitle Value to which the attribute "title" should be set.
     */
    public Builder setTitle( String pTitle ) {
      // Assign value to attribute
      title = pTitle;
      return this;
    }

    /**
     * Method sets the attribute "status".
     * 
     * @param pStatus Value to which the attribute "status" should be set.
     */
    public Builder setStatus( int pStatus ) {
      // Assign value to attribute
      status = pStatus;
      return this;
    }

    /**
     * Method sets the attribute "detail".
     * 
     * @param pDetail Value to which the attribute "detail" should be set.
     */
    public Builder setDetail( String pDetail ) {
      // Assign value to attribute
      detail = pDetail;
      return this;
    }

    /**
     * Method sets the attribute "instance".
     * 
     * @param pInstance Value to which the attribute "instance" should be set.
     */
    public Builder setInstance( String pInstance ) {
      // Assign value to attribute
      instance = pInstance;
      return this;
    }

    /**
     * Method creates a new instance of class Problem. The object will be initialized with the values of the builder.
     * 
     * @return Problem Created object. The method never returns null.
     */
    public Problem build( ) {
      return new Problem(this);
    }
  }

  /**
   * Method returns the attribute "type".
   * 
   * @return String Value to which the attribute "type" is set.
   */
  public String getType( ) {
    return type;
  }

  /**
   * Method returns the attribute "title".
   * 
   * @return String Value to which the attribute "title" is set.
   */
  public String getTitle( ) {
    return title;
  }

  /**
   * Method returns the attribute "status".
   * 
   * @return int Value to which the attribute "status" is set.
   */
  public int getStatus( ) {
    return status;
  }

  /**
   * Method returns the attribute "detail".
   * 
   * @return String Value to which the attribute "detail" is set.
   */
  public String getDetail( ) {
    return detail;
  }

  /**
   * Method returns the attribute "instance".
   * 
   * @return String Value to which the attribute "instance" is set.
   */
  public String getInstance( ) {
    return instance;
  }

  /**
   * Method returns a StringBuilder that can be used to create a String representation of this object. the returned
   * StringBuilder also takes care about attributes of super classes.
   *
   * @return {@link StringBuilder} StringBuilder representing this object. The method never returns null.
   */
  protected StringBuilder toStringBuilder( ) {
    StringBuilder lBuilder = new StringBuilder();
    lBuilder.append("{\n");
    if (type != null) {
      lBuilder.append("  \"type\": \"");
      lBuilder.append(type);
      lBuilder.append('"');
    }

    if (title != null) {
      lBuilder.append(",\n");
      lBuilder.append("  \"title\": \"");
      lBuilder.append(title);
      lBuilder.append('"');
    }

    lBuilder.append(",\n");
    lBuilder.append("  \"status\": ");
    lBuilder.append(status);

    if (detail != null) {
      lBuilder.append(",\n");
      lBuilder.append("  \"detail\": \"");
      lBuilder.append(detail);
      lBuilder.append('"');
    }

    if (instance != null) {
      lBuilder.append(",\n");
      lBuilder.append("  \"instance\": \"");
      lBuilder.append(instance);
      lBuilder.append('"');
    }
    lBuilder.append("\n}");

    return lBuilder;
  }

  /**
   * Method creates a new String with the values of all attributes of this class. All references to other objects will
   * be ignored.
   * 
   * @return {@link String} String representation of this object. The method never returns null.
   */
  @Override
  public String toString( ) {
    return this.toStringBuilder().toString();
  }
}
